name: Run Image Stitching Script

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 当对 main 分支创建 PR 时触发
permissions:
  contents: write  # 允许对代码库的写入权限
jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出当前仓库代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # 设置 Python 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python numpy  # 安装必要的依赖包

    - name: Run image stitching script
      run: |
        python auto_pack_img.py  # 运行你的 Python 脚本（替换为你的脚本文件名）

    - name: Save stitched image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: auto_img_zh_cn    # 上传生成的图片作为 artifact
        path: auto_img_zh_cn.png  # 替换为你生成图片的路径

#    - name: Save stitched image as artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: auto_img_en    # 上传生成的图片作为 artifact
#        path: auto_img_en.png  # 替换为你生成图片的路径
#    - name: Commit and push updated file
#      run: |
#        git config --global user.name "github-actions[bot]"
#        git config --global user.email "github-actions[bot]@users.noreply.github.com"
#        git add auto_img_zh_cn.png  # 添加你想要提交的文件
#        git add auto_img_en.png
#        git commit -m "Update file with new data"
#        git push origin main  # 推送更改回 main 分支
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 Token 推送更改
